name: 'citybikes_dbt'
version: '1.0.0'
config-version: 2

profile: 'citybikes'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  citybikes_dbt:
    +materialized: table
    staging:
      +materialized: view
    analytics:
      +materialized: table